/** Thin caller for the Fetchworks YouTube Transcript Scraper on Apify. */

const ACTOR = "fetchworks~youtube-transcript-scraper";
/** Jobs expected to yield fewer videos than this run on the synchronous endpoint. */
const SYNC_LIMIT = 60;
const DATASET_PAGE_SIZE = 1000;
const POLL_INTERVAL_MS = 3000;
const MAX_WAIT_MS = 30 * 60 * 1000;

export interface ActorInput {
  videoUrls?: string[];
  channelUrls?: string[];
  maxVideosPerChannel?: number;
  playlistUrls?: string[];
  searchQueries?: string[];
  maxSearchResults?: number;
  languages?: string[];
  preferAutoGenerated?: boolean;
  translateTo?: string;
  outputFormats?: ("segments" | "text" | "srt" | "vtt")[];
  includeMetadata?: boolean;
  includeChapters?: boolean;
}

export interface TranscriptItem {
  videoId: string;
  url: string;
  status: string;
  [key: string]: unknown;
}

export class ApifyError extends Error {
  statusCode?: number;

  constructor(message: string, statusCode?: number) {
    super(message);
    this.name = "ApifyError";
    this.statusCode = statusCode;
  }
}

export interface RunnerOptions {
  token: string;
  baseUrl?: string;
  pollIntervalMs?: number;
  maxWaitMs?: number;
}

/** Runs the actor: synchronously for small jobs, run + poll for large ones. */
export async function runActor(
  input: ActorInput,
  expectedVideos: number,
  options: RunnerOptions,
): Promise<TranscriptItem[]> {
  const baseUrl = (options.baseUrl ?? "https://api.apify.com").replace(/\/+$/, "");
  const { token } = options;

  if (expectedVideos < SYNC_LIMIT) {
    return (await request(
      "POST",
      `${baseUrl}/v2/acts/${ACTOR}/run-sync-get-dataset-items?token=${token}&clean=true`,
      input,
    )) as TranscriptItem[];
  }

  const started = (await request("POST", `${baseUrl}/v2/acts/${ACTOR}/runs?token=${token}`, input)) as {
    data: { id: string; status: string; defaultDatasetId: string };
  };

  const pollInterval = options.pollIntervalMs ?? POLL_INTERVAL_MS;
  const deadline = Date.now() + (options.maxWaitMs ?? MAX_WAIT_MS);
  let status = started.data.status;
  const runId = started.data.id;

  while (status === "READY" || status === "RUNNING") {
    if (Date.now() >= deadline) {
      throw new ApifyError(`timed out waiting for actor run ${runId} (still ${status})`);
    }
    await sleep(pollInterval);
    const res = (await request("GET", `${baseUrl}/v2/actor-runs/${runId}?token=${token}`)) as {
      data: { status: string };
    };
    status = res.data.status;
  }

  if (status !== "SUCCEEDED") {
    throw new ApifyError(`actor run ${runId} finished with status ${status}`);
  }

  const items: TranscriptItem[] = [];
  for (let offset = 0; ; offset += DATASET_PAGE_SIZE) {
    const page = (await request(
      "GET",
      `${baseUrl}/v2/datasets/${started.data.defaultDatasetId}/items?token=${token}&clean=true&format=json&offset=${offset}&limit=${DATASET_PAGE_SIZE}`,
    )) as TranscriptItem[];
    items.push(...page);
    if (page.length < DATASET_PAGE_SIZE) return items;
  }
}

async function request(method: "GET" | "POST", url: string, body?: unknown): Promise<unknown> {
  const res = await fetch(url, {
    method,
    headers: body === undefined ? undefined : { "content-type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  if (!res.ok) {
    let detail = "";
    try {
      const parsed = (await res.json()) as { error?: { message?: string } };
      detail = parsed?.error?.message ?? "";
    } catch {
      // non-JSON error body; the status line is enough
    }
    throw new ApifyError(`Apify API ${method} ${res.status}${detail ? `: ${detail}` : ""}`, res.status);
  }
  return res.json();
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
