import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { runActor, type ActorInput, type RunnerOptions, type TranscriptItem } from "./apify.js";

export const SERVER_NAME = "fetchworks-youtube-transcripts";
export const SERVER_VERSION = "0.1.0";

const sharedOptions = {
  languages: z
    .array(z.string())
    .optional()
    .describe('Language priority list (ISO codes, e.g. ["en", "de"]). First available caption track wins. Default ["en"].'),
  preferAutoGenerated: z
    .boolean()
    .optional()
    .describe("Prefer auto-generated (ASR) captions over manual ones. Default false."),
  translateTo: z
    .string()
    .optional()
    .describe('Target language code (e.g. "es") for YouTube caption auto-translation. Best-effort.'),
  outputFormats: z
    .array(z.enum(["segments", "text", "srt", "vtt"]))
    .optional()
    .describe('Transcript representations to include. Default ["text"] for compact tool output.'),
  includeMetadata: z
    .boolean()
    .optional()
    .describe("Include title, channel, duration, views, publish date. Default true."),
  includeChapters: z.boolean().optional().describe("Include video chapters. Default false."),
};

type SharedArgs = {
  languages?: string[];
  preferAutoGenerated?: boolean;
  translateTo?: string;
  outputFormats?: ("segments" | "text" | "srt" | "vtt")[];
  includeMetadata?: boolean;
  includeChapters?: boolean;
};

function baseInput(args: SharedArgs): ActorInput {
  const input: ActorInput = { outputFormats: args.outputFormats ?? ["text"] };
  if (args.languages?.length) input.languages = args.languages;
  if (args.preferAutoGenerated !== undefined) input.preferAutoGenerated = args.preferAutoGenerated;
  if (args.translateTo) input.translateTo = args.translateTo;
  if (args.includeMetadata !== undefined) input.includeMetadata = args.includeMetadata;
  if (args.includeChapters !== undefined) input.includeChapters = args.includeChapters;
  return input;
}

function toResult(items: TranscriptItem[]): { content: { type: "text"; text: string }[]; isError?: boolean } {
  return { content: [{ type: "text", text: JSON.stringify(items, null, 2) }] };
}

function toError(error: unknown): { content: { type: "text"; text: string }[]; isError: true } {
  const message = error instanceof Error ? error.message : String(error);
  return { content: [{ type: "text", text: message }], isError: true };
}

export function createServer(runner: RunnerOptions): McpServer {
  const server = new McpServer({ name: SERVER_NAME, version: SERVER_VERSION });

  server.registerTool(
    "get_youtube_transcript",
    {
      title: "Get YouTube transcript(s)",
      description:
        "Get transcripts for one or more YouTube videos (URLs, Shorts/youtu.be links, or bare 11-character video IDs). " +
        "Returns one item per video with an honest status (ok, no_captions, blocked, live_stream, age_restricted, " +
        "unavailable, translation_unavailable, po_token_required, error) and the transcript as text/segments/SRT/VTT.",
      inputSchema: {
        videos: z
          .array(z.string())
          .min(1)
          .describe("YouTube video URLs or bare 11-character video IDs. One transcript per video."),
        ...sharedOptions,
      },
    },
    async ({ videos, ...args }) => {
      try {
        const input = baseInput(args);
        input.videoUrls = videos;
        return toResult(await runActor(input, videos.length, runner));
      } catch (error) {
        return toError(error);
      }
    },
  );

  server.registerTool(
    "get_channel_transcripts",
    {
      title: "Get channel transcripts",
      description:
        "Get transcripts for a YouTube channel's most recent uploads (newest first). " +
        "Accepts a channel URL or a bare @handle. Bounded by maxVideos (default 10 to keep responses fast).",
      inputSchema: {
        channel: z.string().describe("Channel URL (youtube.com/@handle, /channel/UC…, /c/…, /user/…) or bare @handle."),
        maxVideos: z
          .number()
          .int()
          .min(1)
          .optional()
          .describe("Upper bound on videos taken from the channel, newest first. Default 10."),
        ...sharedOptions,
      },
    },
    async ({ channel, maxVideos, ...args }) => {
      try {
        const bound = maxVideos ?? 10;
        const input = baseInput(args);
        input.channelUrls = [channel];
        input.maxVideosPerChannel = bound;
        return toResult(await runActor(input, bound, runner));
      } catch (error) {
        return toError(error);
      }
    },
  );

  server.registerTool(
    "search_youtube_transcripts",
    {
      title: "Search YouTube and get transcripts",
      description:
        "Search YouTube and get transcripts for the top video results. " +
        "Bounded by maxResults (default 5 to keep responses fast).",
      inputSchema: {
        query: z.string().describe("YouTube search query."),
        maxResults: z
          .number()
          .int()
          .min(1)
          .optional()
          .describe("Upper bound on videos taken from the search results. Default 5."),
        ...sharedOptions,
      },
    },
    async ({ query, maxResults, ...args }) => {
      try {
        const bound = maxResults ?? 5;
        const input = baseInput(args);
        input.searchQueries = [query];
        input.maxSearchResults = bound;
        return toResult(await runActor(input, bound, runner));
      } catch (error) {
        return toError(error);
      }
    },
  );

  return server;
}
